name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install dependencies
        run: DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y \
          $(cat .circleci/build-dependencies.txt)
      - name: Build contrib
        run: make -C contrib -j $(nproc)
      - name: Build 
        run: |
          . ./contrib/env.sh
          make -j $(nproc)
      - name: Run tests
        run: make test
  
